apiVersion: v1
kind: Service
metadata:
  name: app-load-balancer
  labels:
    name: app-load-balancer
spec:
  selector:
    app: green-deployment
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
